
public class PrimaClasse {
	
	/*
	 * JAVA E' FORTEMENTE TIPIZZATO!!!!
	 * NON FA E NON USA NULLA SE NON SA ESATTAMENTE COS'È
	 * OGNI CARATTERE HA UN UNICO SCOPO DI UTILIZZO
	 * E' TUTTO UN GIRAMENTO DI SCATOLE
	 * COME IN UNA MATRIOSCA LE LIBRERIE SONO FORMATE DA SCATOLE
	 * CHE CONTENGONO ALTRE SCATOLE
	 * IN OGNI SCATOLA E'RAGRUPPATO UNA ABILITÀDI JAVA
	 * POSSIAMO USARE QUELLE CHE CI METTE A DISPOSIZIONE SI DICE CHE
	 * O CREARNE DELLE ALTRE
	 * SE USIAMO QUELLE CHE CI METTE A DISPOSIZIONE SI DICE CHE
	 * LE EREDITIAMO. QUANDO ABBIAMO CREATO QEUSTA CLASSE
	 * ABBIAMO EREDITATO IL KNOW-HOW DALLA CLASSA JAVA.LANG.OBJECT
	 * OVVERO SAPRÀ GESTIRE GLI OGGETTI DEL LINGUAGGIO JAVA
	 * LA CLASSE DA CUI EREDITIAMO SI CHIAMA SUPERCLASSE
	 */

	public static void main(String[] args) {
		
		
		/*
		 * NELLE CLASSI POTREMMO TROVARE
		 * ATTRIBUTI: QUELLO CHE LA CLASSE È
		 * METODI: QUELLO CHE LA CLASSE FA
		 * IL METODO MAIN COSA SA FARE?
		 * SA AVVIARE LA NOSTRA APPLICAZIONE
		 * E' UN METODO PUBBLIC
		 * E' UN METODO STATIC (NON DINAMINCO) SI RIFERISCE ALLA CLASSE 
		 *                                             NON ALLE ISTANZE
		 * E' UN METODO VOID -  NON RESTITUISCE VALORI MA OPERAZIONI
		 * PERCH�' E' UN METODO?
		 * JAVA LO RICONOSCE PERCH� ACCANTO HA UNA PARENTESI TONDA
		 * LE TONDE SERVONO SOLO HA DARE ARGOMENTI AI METODI
		 * GLI ARGOMENTI DEI METODI SERVONO AI METODI A FARE QUELLO CHE SANNO FARE
		 * L'ARGOMENTO DI MAIN E' String[] args (ARRAY DI STRINGHE)
		 * PERCHÈ L'OUTPUT DEL NOSTRO PROGRAMMA NON E' ALTRO CHE UNA
		 * SEQUENZA DI STRINGHE CHE TROVIAMO IN CONSOLE
		 * JAVA NON HA UNA INTERFACCIA GRAFICA!
		 * HA SOLO UNA CONSOLE DI STRINGHE COME OUTPUT 
		 */
		
		/*
		*LA PIÙ PICCOLA SCATOLA DI JAVA SONO LE VARIABILI PRIMITIVE
		*COME SONO FATTE E A COSA SERVONO?
		*1 CONTENGONO UN VALORE 
		*2 HANNO UN NOME
		*3 HANNO UN TIPO
		*/
		
		//VARIABILI PRIMITIVE
		//NUEMRICA - int
		
		int numero; //MOMENTO DICHIARATIVO
		numero=5; //MOMENTO DI INIZIALIZZAZIONE
		//_ OPERATORE DI ASEGNAZIONE
		
		//I DUE MOMENTI POSSONO ESSERE UNITI NELLA STESSA ISTRUZIONE
		int altronumero = 3; //DUE MOMENTI NELLA STESSA ISTRUZIONE
		
		//NUMERI RELATIVI (IN VIRGOLA MOBILE)
		double numerorelativo = 10.3; 
		
		//VARIABILE - STATO
		//STATO - BOOLEANA
		//PUÒ CONTENERE SOLO 2 VALORI - TRUE E FALSE
		//MI CONSENTIRÀ DI FARE I CONFRONTI
		
		boolean stato = true;
		
		//PER I TESTI COME VARIABILE PRIMITIVA JAVA MI DA IL CHAR
		//CARATTERE
		
		char lettera = 'n'; //APICI SINGOLI!!
		
		//COME FA ALLORA JAVA A GESTIRE LE PAROLE???
		//PER JAVA UNA PAROLA "STRINGA" E'UNA SEQUENZA DI CHAR
		
		//GENTILE CONCESSIONE DI JAVA!!!
		//LA VARIABILE OGGETTO STRINGA PU� ESSERE USATA COME VARIABILE PRIMITIVA
		//MA ATTENZIONE NON LO E'!!
		
		String nome = "Nicola"; //VALORE CON I DOPPI APICI
		
		/*
		 * UNA VARIABILE OGGETTO A DIFFERENZA DI UNA VARIABILE PRIMITIVA 
		 * AL SUO INTERNO
		 * ATTRIBUTI
		 * METODI
		 * - COME NELLE CLASSI QUINDI??
		 * SI GLI OGGETTI SONO ISTANZE DELLE CLASSI
		 * PER CAPIRCI LE CLASSI SONO LA FABBRICA 
		 * GLI OGGETTI (LE ISTANZE) SONO I PRODOTTI DELLA FABBRICA
		 */
		
		/*
		 * MA JAVA E' FORTEMENTE TIPIZZATO COME DOVREBBE
		 * ESSERE CREATO UN OGGETTO STRINGA SE NON AVESSIMO
		 * LA GENTILE CONCESSIONE DI JAVA??
		 * TUTTI GLI OGGETTI VENGONO ISTANZIATI CON LA PAROLA RISERVATA NEW
		 */
		
		//UNA STRINGA DOVREBBE E'PUÒ COMUNQUE ESSEERE ISTANZIATA COSÌ
		
		String mionome = new String("Pippo");
		//SPIEGHIAMO QUESTA ISTRUZIONE
		//A SINISTRA DELL'UGUALE NON CAMBIA NULLA
		//A DESTRA HO UN PAROLINA RISERVATA NEW
		//MA POI HO UN METODO CHE HA UN ARGOMENTO VALORE
		//QUINDI string E'UNA CLOASSE (FABBRICA)
		//CHE QUI STA ISTANZIANDO 
		//IL METODO String CHE HA LO STESSO NOME DELLA CLASSE
		//SI DICE COSTRUTTORE
		
		
	} //FINISCE QUI

}
