
public class CicloDefinito {

	public static void main(String[] args) {
		
		/*
		 * UN CICLO E' DEFINITO QUANDO
		 * SO A MONTE QUANTE VOLTE LE ISTRUZIONI DEVONO CICLARE
		 * PER GESTIRE QUESTO CICLO JAVA USA 
		 * IL COSTRUTTO FOR
		 * IL COSTRUTTO FOR HA SEMPRE LA STESSA STRUTTURA
		 * 1 - PAROLA RISERVATA FOR
		 * 2 - PARENTESI TONDE PER IL CONFRONTO
		 * 		PARTICOLARITA' DEL COSTRUTTO
		 * 		E CHE NELLE TONDE ABBIAMO 3 ELEMENTI
		 * 		A - CREAZIONE DI UNA VARIABILE ITERATRICE
		 * 		B - CONFRONTO
		 * 		C PASSO DELLA VARIABILE ITERATRICE
		 * 3 - ISTRUZIONI TRA LE GRAFFE
		 * 
		 * L'ISTRUZIONE QUINDI SI RIPETE OGNI VOLTA
		 * DOPO AVER CONFRONTATO IL VALORE DI UNA VARIABILE ITERATRICE
		 * DI SOLITO CHIAMATA I, A CUI ASSEGNAMO ANCHE UN PASSO
		 * DI AVANZAMENTO
		 * 
		 * 
		 */
		
		/*
		 * PER GESTIRE IL PASSO MOLTO SPESSO VIENE UNATO UN OPERATORE
		 * PARTICOLARE
		 * 
		 * OPERATORE UNARIO DI INCREMENTO O DECREMENTO
		 * 
		 * a++   -> a = a + 1
		 * a--   -> a = a - 1
		 * 
		 *  QUESTI OPERATORI UNARI POSSONO ESSERE
		 *  PREPOSTI - MESSI PRIMA
		 *  POSTPOSTI - MESSI DOPO
		 *  
		 *  ++a 
		 *  --a
		 * 
		 * QUAL'E' LA DIFFERENZA?
		 * STA NEL QUANDO VIENE USATO L'INCREMENTO
		 * SE POSTPOSTO IL VALORE VIENE PRIMA USATO E POI VARIA
		 * SE PREPOSTO IL VALORE VIENE SUBITO VARIATO E POI USATO
		 */
		
		/*
		int a = 5;
		
		System.out.println(--a);
		System.out.println(a);
		*/
		
		/*
		 * IL PASSO UNARIO E' MOLTO USATO NEL CICLO FOR
		 */
		
		for (int i = 0; i < 10; i += 5) {
			
			System.out.println("Ciao " + i);
			
		}
		
		System.out.println("---------------------");
		
		//ATTENZIONE E' POSSIBILE USARE L'OPERATORE DI ASSEGNAZIONE 
		//INCREMENTALE O DECREMENTALE
		
		/*
		 * += - INCREMENTALE
		 * -= DECREMENTALE
		 */
		
		
		for (int i = 10; i > 0; i -= 2) {
			
			System.out.println("Ciao " + i);
			
		}
		
		/*
		 * NB: HO DICHIARATO E USATO 2 VOLTE LA VARIABILE i
		 * OGNI VARIABILE HA LA SUA VISIBILITA'
		 * SE DICHIARATA IN UN METODO SI VEDR� IN TUTTO IL METODO
		 * SE DICHIARATA IN UN COSTRUTTO
		 * SI VEDRA' SOLO IN QUEL COSTRUTTO
		 * AD ESEMPIO LA VARIABILE ITERATRICE DI UN FOR
		 * NASCE E MUORE CON IL FOR
		 */
		
		
	}

}
