import java.util.Scanner;

public class OggettoSystem {

	public static void main(String[] args) {
		
		/*
		 * SAPPIAMO CHE UN PROGRAMMA HA 3 MOMENTI
		 * 1 INPUT
		 * 2 COMPUT
		 * 3 OUTPUT
		 */
		
		/*
		 * PER GESTIRE I MOMENTI DI INPUT E DI OUTPUT
		 * HO BISOGNO DI DIALOGARE CON IL SISTEMA (MACCHINA)
		 * DEVO CHIAMARE UNA CLASSE CHE MI GESTISCA QUESTA CORRISPOINDENZA
		 * JAVA MI FORNISCE LA CLASSE SYSTEM
		 * SYSTEM HA IL SUO INTERNO UNA SOTTOCLASSE IN E UNA OUT
		 * OUT SERVE PER SCRIVERE IN CONSOLE
		 * DICE AL SISTEMA DI SCRIVERE SULLA CONSOLE
		 */
		
		/*
		 * JAVA PUÒ GESTIRE ALL'INTERNO DELLO STESSO OGGETTO
		 * PIÙ METODI CON LO STESSO NOME.
		 * PURCHÈ QUESTI ACCOLGANO PARAMENTRI DI DIVERSO TIPO
		 * QUESTA CAPACITÀ DI CHIAMA POLIMORFISMO
		 */
		
		/*
		System.out.println("Ciao");
		System.out.println(5);
		System.out.println(true);
		System.out.println('a');
		System.out.println(5.30);
		/*
		 
		/*
		 * IN INGRESSO LA SITUAZIONE E'PIÙ COMPLICATA PER JAVA
		 * DEVE ACCETTARE UN VALORE ESPRESSO DALL'UTENTE
		 * MA SI FIDA CHE SIA IL TIPO DI VALORE CHE GLI SERVE???
		 * ASSOLUTAMENTE NO!
		 * PER POTER CONTROLLARE CREA UN CANALE DI COMUNICAZIONE
		 * CHE SI CHIAMA SCANNER
		 * LO SCANNER  SARÀ UNA ISTANZA DELLA CLASSE SCANNER
		 * CHE AGIRÀ SULL'OGGETTO SYSTEM
		 * E' COME UN TUBO DI COMUNICAZIONE TRA L'UTENTE E IL SISTEMA
		 * QUANDO IL DATO CHE GLI DARÀ L'UTENTE PASSA NEL TUBO
		 * JAVA POTRÀ CONTROLLARLO PER VEDERE SE E'IL TIPO
		 * DI VALORE CHE SI APSETTA
		 * IN REALTÀ JAVA NON PUÒ USARE UN DATO MESSO PER ARIA
		 * HA BISOGNO DI APPOGGIARLO IN UNA SCATOLA(VARIABILE)
		 * E DI CHE TIPO DEVE ESSERE LA SCATOLA???
		 * SE L'UTENTE DA UN VALORE CHE POI NON POSSO METTERE
		 * NELLA SCATOLA CHE JAVA HA PREPARATO I PROGRAMMA
		 * CREA UN ECCEZIONE BLOCCANTE (CRASH!)
		 * 
		 */
		
		// string nome = new String ("Pippo");
		//CREO UN OGGETTO DI TIPO SCANNER
		//PER CONTROLLAARE IL FLUSSO IN INGRESSO
		Scanner input = new Scanner(System.in);
		
		
		System.out.println("Come ti chiami?:");
		//CREO UNA VARIABILE STRINGA PER ACCOGLIERE
		//LA PROSSIMA STRINGA CHE PASSA NEL TUBO INPUT (DI TIPO SCANNER)
		String nome = input.nextLine();	//QUI IL PROGRAMMA SI FERMA!!
		                                //ASPETTA L'INPUT DELL'UTENTE
		System.out.println("Ciao " + nome);
		

	}

}
